# Generated by Django 3.1 on 2020-08-30 03:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Application',
            fields=[
                ('sno', models.AutoField(primary_key=True, serialize=False)),
                ('lab_no', models.IntegerField()),
                ('name', models.CharField(max_length=80)),
                ('age', models.IntegerField(default=0)),
                ('sex', models.CharField(max_length=10)),
                ('recieved_on', models.DateField(auto_now=True)),
                ('ref_by', models.CharField(default='Dr.Self', max_length=50)),
                ('cost', models.IntegerField(default=0)),
                ('checked', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Test',
            fields=[
                ('sno', models.AutoField(primary_key=True, serialize=False)),
                ('test', models.CharField(max_length=50)),
                ('price', models.IntegerField(default=0)),
                ('device', models.CharField(max_length=300)),
            ],
        ),
        migrations.CreateModel(
            name='Value',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lab_no', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Record',
            fields=[
                ('sno', models.AutoField(primary_key=True, serialize=False)),
                ('lab_no', models.IntegerField()),
                ('test', models.CharField(max_length=70)),
                ('application', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lab.application')),
            ],
        ),
    ]
