# Generated by Django 3.1 on 2020-08-30 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lab', '0002_auto_20200830_0341'),
    ]

    operations = [
        migrations.AddField(
            model_name='record',
            name='finding',
            field=models.CharField(default='', max_length=30),
        ),
        migrations.AddField(
            model_name='record',
            name='ref',
            field=models.CharField(default='', max_length=30),
        ),
    ]
