# Generated by Django 3.1 on 2021-03-13 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lab', '0003_auto_20200910_1912'),
    ]

    operations = [
        migrations.AddField(
            model_name='test',
            name='range1',
            field=models.CharField(default='', max_length=50),
        ),
    ]
